"""empty message

Revision ID: 4aeed649d132
Revises: f74bcd05183f
Create Date: 2019-09-26 06:48:59.500420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeed649d132'
down_revision = 'f74bcd05183f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data', 'category', ['category_id'], ['id'])
    op.drop_column('data', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'category_id')
    # ### end Alembic commands ###
