"""empty message

Revision ID: 93ac911169d3
Revises: 0a23598a6cb3
Create Date: 2019-10-02 15:33:39.496454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ac911169d3'
down_revision = '0a23598a6cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maillist', sa.Column('remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maillist', 'remark')
    # ### end Alembic commands ###
